// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: acr.proto
#ifndef GRPC_acr_2eproto__INCLUDED
#define GRPC_acr_2eproto__INCLUDED

#include "acr.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace grpc {
class CompletionQueue;
class Channel;
class ServerCompletionQueue;
class ServerContext;
}  // namespace grpc

namespace lacr {

class Classify final {
 public:
  static constexpr char const* service_full_name() {
    return "lacr.Classify";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status Recognise(::grpc::ClientContext* context, const ::lacr::Request& request, ::lacr::Response* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lacr::Response>> AsyncRecognise(::grpc::ClientContext* context, const ::lacr::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lacr::Response>>(AsyncRecogniseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lacr::Response>> PrepareAsyncRecognise(::grpc::ClientContext* context, const ::lacr::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::lacr::Response>>(PrepareAsyncRecogniseRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      virtual void Recognise(::grpc::ClientContext* context, const ::lacr::Request* request, ::lacr::Response* response, std::function<void(::grpc::Status)>) = 0;
      virtual void Recognise(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::lacr::Response* response, std::function<void(::grpc::Status)>) = 0;
    };
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::lacr::Response>* AsyncRecogniseRaw(::grpc::ClientContext* context, const ::lacr::Request& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::lacr::Response>* PrepareAsyncRecogniseRaw(::grpc::ClientContext* context, const ::lacr::Request& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel);
    ::grpc::Status Recognise(::grpc::ClientContext* context, const ::lacr::Request& request, ::lacr::Response* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lacr::Response>> AsyncRecognise(::grpc::ClientContext* context, const ::lacr::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lacr::Response>>(AsyncRecogniseRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lacr::Response>> PrepareAsyncRecognise(::grpc::ClientContext* context, const ::lacr::Request& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::lacr::Response>>(PrepareAsyncRecogniseRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void Recognise(::grpc::ClientContext* context, const ::lacr::Request* request, ::lacr::Response* response, std::function<void(::grpc::Status)>) override;
      void Recognise(::grpc::ClientContext* context, const ::grpc::ByteBuffer* request, ::lacr::Response* response, std::function<void(::grpc::Status)>) override;
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::lacr::Response>* AsyncRecogniseRaw(::grpc::ClientContext* context, const ::lacr::Request& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::lacr::Response>* PrepareAsyncRecogniseRaw(::grpc::ClientContext* context, const ::lacr::Request& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Recognise_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Recognise(::grpc::ServerContext* context, const ::lacr::Request* request, ::lacr::Response* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_Recognise : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithAsyncMethod_Recognise() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Recognise() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognise(::grpc::ServerContext* context, const ::lacr::Request* request, ::lacr::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognise(::grpc::ServerContext* context, ::lacr::Request* request, ::grpc::ServerAsyncResponseWriter< ::lacr::Response>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Recognise<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_Recognise : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithCallbackMethod_Recognise() {
      ::grpc::Service::experimental().MarkMethodCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::lacr::Request, ::lacr::Response>(
          [this](::grpc::ServerContext* context,
                 const ::lacr::Request* request,
                 ::lacr::Response* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   return this->Recognise(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithCallbackMethod_Recognise() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognise(::grpc::ServerContext* context, const ::lacr::Request* request, ::lacr::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Recognise(::grpc::ServerContext* context, const ::lacr::Request* request, ::lacr::Response* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  typedef ExperimentalWithCallbackMethod_Recognise<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Recognise : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithGenericMethod_Recognise() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Recognise() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognise(::grpc::ServerContext* context, const ::lacr::Request* request, ::lacr::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Recognise : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithRawMethod_Recognise() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Recognise() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognise(::grpc::ServerContext* context, const ::lacr::Request* request, ::lacr::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestRecognise(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_Recognise : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    ExperimentalWithRawCallbackMethod_Recognise() {
      ::grpc::Service::experimental().MarkMethodRawCallback(0,
        new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
          [this](::grpc::ServerContext* context,
                 const ::grpc::ByteBuffer* request,
                 ::grpc::ByteBuffer* response,
                 ::grpc::experimental::ServerCallbackRpcController* controller) {
                   this->Recognise(context, request, response, controller);
                 }));
    }
    ~ExperimentalWithRawCallbackMethod_Recognise() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Recognise(::grpc::ServerContext* context, const ::lacr::Request* request, ::lacr::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual void Recognise(::grpc::ServerContext* context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response, ::grpc::experimental::ServerCallbackRpcController* controller) { controller->Finish(::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "")); }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_Recognise : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service *service) {}
   public:
    WithStreamedUnaryMethod_Recognise() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler< ::lacr::Request, ::lacr::Response>(std::bind(&WithStreamedUnaryMethod_Recognise<BaseClass>::StreamedRecognise, this, std::placeholders::_1, std::placeholders::_2)));
    }
    ~WithStreamedUnaryMethod_Recognise() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status Recognise(::grpc::ServerContext* context, const ::lacr::Request* request, ::lacr::Response* response) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedRecognise(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::lacr::Request,::lacr::Response>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_Recognise<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_Recognise<Service > StreamedService;
};

}  // namespace lacr


#endif  // GRPC_acr_2eproto__INCLUDED
